language: java

jdk:
- oraclejdk7

env: 
  global: 
  - RELEASE_CANDIDATE=$(.travis.d/release_candidate.sh)

install:
- .travis.d/install.sh

script:
- .travis.d/script.sh

after_success:
- .travis.d/after_success.sh
